version: '3.4'

volumes:
  mysql-db2: {}

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - mysql-db2:/var/lib/mysql
    ports:
      - '3305:3306'
    restart: always

  djserver:
    build: ./
    env_file: .env
    ports:
      - '7000:7000'
    depends_on:
      - mysql
    command: ./run.sh