# Generated by Django 3.1.7 on 2021-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='catId', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='proName', default='', max_length=100)),
                ('category_description', models.CharField(db_column='proDescription', default='', max_length=255)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
                'unique_together': {('category_name', 'category_description')},
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(db_column='selId', primary_key=True, serialize=False)),
                ('nick_name', models.CharField(db_column='selNick', default='', max_length=64)),
                ('corporate_name', models.CharField(db_column='selCorporateName', default='', max_length=255)),
                ('seller_cnpj', models.IntegerField(db_column='selCNPJ', default=0)),
                ('contact_email', models.EmailField(db_column='selContactEmail', default='', max_length=100)),
                ('phone_number', models.IntegerField(db_column='selPhoneNumber')),
                ('address', models.CharField(db_column='selAddress', default='', max_length=255)),
            ],
            options={
                'db_table': 'Seller',
                'managed': True,
                'unique_together': {('nick_name', 'corporate_name', 'contact_email', 'address', 'seller_cnpj', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.AutoField(db_column='mplId', primary_key=True, serialize=False)),
                ('market_place_name', models.CharField(db_column='mplName', default='', max_length=100)),
                ('market_place_description', models.CharField(db_column='mplDescription', default='', max_length=255)),
                ('site', models.FloatField(db_column='mplSite', default=0)),
                ('contact_email', models.EmailField(db_column='mplContactEmail', default='', max_length=100)),
                ('phone_number', models.IntegerField(db_column='mplPhoneNumber', default=0)),
                ('technical_contact', models.CharField(db_column='mplTechnicalContact', default='', max_length=255)),
            ],
            options={
                'db_table': 'MarketPlace',
                'managed': True,
                'unique_together': {('market_place_name', 'site', 'market_place_description', 'contact_email', 'phone_number', 'technical_contact')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='proId', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='proName', default='', max_length=100)),
                ('product_description', models.CharField(db_column='proDescription', default='', max_length=255)),
                ('product_value', models.FloatField(db_column='proValue', default=0)),
                ('categories', models.ManyToManyField(db_column='proCategories', related_name='product', to='olist.Category')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
                'unique_together': {('product_name', 'product_value', 'product_description')},
            },
        ),
    ]
