# Generated by Django 3.1.7 on 2021-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='phone_number',
            field=models.BigIntegerField(db_column='mplPhoneNumber', default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.BigIntegerField(db_column='selPhoneNumber'),
        ),
    ]
