# Generated by Django 3.1.7 on 2021-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0002_auto_20210220_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='site',
            field=models.CharField(db_column='mplSite', default=0, max_length=255),
        ),
    ]
