# Generated by Django 3.1.7 on 2021-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0003_auto_20210220_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(db_column='proCategories', related_name='products', to='olist.Category'),
        ),
    ]
