# Generated by Django 3.1.7 on 2021-02-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0004_auto_20210220_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_cnpj',
            field=models.BigIntegerField(db_column='selCNPJ', default=0),
        ),
    ]
