# Generated by Django 3.1.7 on 2021-02-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0005_auto_20210221_0415'),
        ('olist', '0005_auto_20210221_1626'),
    ]

    operations = [
    ]
